services:
  - type: web
    name: hridamrit-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn fit_api:app
    envVars:
      PYTHON_VERSION: 3.10.13
